### ISSUE TITLE
Add multi-Stargate support

### ISSUE THREAD

**Issue by annybs** [edge/discord-bots#3]
At the moment, the bot accesses Stargate API directly to retrieve sessions:

https://github.com/edge/discord-bots/blob/438132d48e0603feb4ab3a712a934184323c0910/src/network-bot/index.ts#L76

When we move to multi-Stargate networking this will need to change, perhaps to use Index instead which effectively aggregates from all Stargates.

**Comment by adamkdean** [comment]
This will need to use https://github.com/edge/index/issues/223 for the data
